server:
  port: 80

spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://47.115.42.52:3306/rbac?serverTimezone=UTC&useSSL=false&amp&useUnicode=true&amp&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
